pipeline {
    agent any
    tools{
         terraform 'Terraform'
    }
    parameters {
        choice(name: 'workspace', choices:['dev','prod'] )
        choice(name: 'action', choices:['apply','destroy'])
    }

    stages {
        stage('aws creditentials') {
            steps {
                withCredentials([string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'), string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')]) {
    // some block
}
            }
        }
        stage('check') {
            steps {
                git branch: 'main', credentialsId: 'github-token', url: 'https://github.com/naghamahmed/Terraform.git'
               
            }
        }

        stage('terraform init') {
            steps {
                sh'terraform init'
            }
        }
        
        stage('terraform action') {  
            steps {
                echo"${action}"
                sh"terraform workspace select ${workspace}"
                sh"terraform ${action} --auto-approve --var-file ${workspace}.tfvars "
            }
        } 
    }

}
